// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SideMenuController from "./side_menu_controller"
application.register("side-menu", SideMenuController)

import SpotifyArtistSearchController from "./spotify_artist_search_controller"
application.register("spotify-artist-search", SpotifyArtistSearchController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import StagePerformanceFormController from "./stage_performance_form_controller"
application.register("stage-performance-form", StagePerformanceFormController)

import TapFeedbackController from "./tap_feedback_controller"
application.register("tap-feedback", TapFeedbackController)

import FavoriteToggleController from "./favorite_toggle_controller"
application.register("favorite-toggle", FavoriteToggleController)

import RevealOnScrollController from "./reveal_on_scroll_controller"
application.register("reveal-on-scroll", RevealOnScrollController)

import PackingListFormController from "./packing_list_form_controller"
application.register("packing-list-form", PackingListFormController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import BulkStagePerformanceFormController from "./bulk_stage_performance_form_controller"
application.register("bulk-stage-performance-form", BulkStagePerformanceFormController)

import SpotifySongSearchController from "./spotify_song_search_controller"
application.register("spotify-song-search", SpotifySongSearchController)

import SpotifySongRowSearchController from "./spotify_song_row_search_controller"
application.register("spotify-song-row-search", SpotifySongRowSearchController)
